#!/usr/bin/env bash
# BeforeItBills — Maestro test runner with markdown report
#
# Usage:
#   export TEST_EMAIL="test@example.com"
#   export TEST_PASSWORD="yourpassword"
#   bash .maestro/run_tests.sh
#
# Optional: run a single flow
#   bash .maestro/run_tests.sh flows/07_home_screen.yaml

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESULTS_DIR="$SCRIPT_DIR/results"
REPORT_FILE="$RESULTS_DIR/report.md"
JUNIT_FILE="$RESULTS_DIR/junit.xml"
SCREENSHOTS_DIR="$RESULTS_DIR/screenshots"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

mkdir -p "$RESULTS_DIR" "$SCREENSHOTS_DIR"

# ── Credentials check ────────────────────────────────────────────────────────
if [[ -z "${TEST_EMAIL:-}" || -z "${TEST_PASSWORD:-}" ]]; then
  echo "ERROR: Set TEST_EMAIL and TEST_PASSWORD before running."
  echo "  export TEST_EMAIL=test@example.com"
  echo "  export TEST_PASSWORD=yourpassword"
  exit 1
fi

# ── Choose target ────────────────────────────────────────────────────────────
if [[ $# -gt 0 ]]; then
  TARGET="$SCRIPT_DIR/$1"
  echo "Running single flow: $TARGET"
else
  TARGET="$SCRIPT_DIR/flows"
  echo "Running all flows in: $TARGET"
fi

# ── Run Maestro ──────────────────────────────────────────────────────────────
echo ""
echo "Starting Maestro tests at $TIMESTAMP"
echo "══════════════════════════════════════════"

PASS=0
FAIL=0
ERRORS=()

# Run each flow individually to capture per-test pass/fail
FLOWS=()
if [[ -d "$TARGET" ]]; then
  while IFS= read -r f; do
    [[ "$f" == *"/utils/"* ]] && continue  # skip utility subflows
    FLOWS+=("$f")
  done < <(find "$TARGET" -name "*.yaml" | sort)
else
  FLOWS=("$TARGET")
fi

for FLOW in "${FLOWS[@]}"; do
  FLOW_NAME=$(basename "$FLOW" .yaml)
  echo -n "  ▶ $FLOW_NAME ... "

  if maestro test \
      --format junit \
      --output "$RESULTS_DIR/${FLOW_NAME}_junit.xml" \
      -e TEST_EMAIL="$TEST_EMAIL" \
      -e TEST_PASSWORD="$TEST_PASSWORD" \
      "$FLOW" > "$RESULTS_DIR/${FLOW_NAME}.log" 2>&1; then
    echo "✅ PASS"
    PASS=$((PASS + 1))
  else
    echo "❌ FAIL"
    FAIL=$((FAIL + 1))
    ERRORS+=("$FLOW_NAME")
  fi
done

TOTAL=$((PASS + FAIL))
echo "══════════════════════════════════════════"
echo "Results: $PASS/$TOTAL passed"
echo ""

# ── Generate markdown report ─────────────────────────────────────────────────
cat > "$REPORT_FILE" << EOF
# BeforeItBills — Maestro Test Report

**Run at**: $TIMESTAMP
**Result**: $PASS / $TOTAL passed

---

## Summary

| | Count |
|---|---|
| ✅ Passed | $PASS |
| ❌ Failed | $FAIL |
| Total | $TOTAL |

EOF

if [[ ${#ERRORS[@]} -gt 0 ]]; then
  echo "## Failed Flows" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  for e in "${ERRORS[@]}"; do
    echo "### ❌ $e" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    tail -30 "$RESULTS_DIR/${e}.log" >> "$REPORT_FILE" 2>/dev/null || true
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" << EOF

---

## All Flows

EOF

for FLOW in "${FLOWS[@]}"; do
  FLOW_NAME=$(basename "$FLOW" .yaml)
  if printf '%s\n' "${ERRORS[@]}" | grep -qx "$FLOW_NAME"; then
    echo "- ❌ \`$FLOW_NAME\`" >> "$REPORT_FILE"
  else
    echo "- ✅ \`$FLOW_NAME\`" >> "$REPORT_FILE"
  fi
done

cat >> "$REPORT_FILE" << EOF

---

## Screenshots

Screenshots saved to: \`$SCREENSHOTS_DIR\`

---

*Generated by \`.maestro/run_tests.sh\`*
EOF

echo "Report written to: $REPORT_FILE"
echo ""

# ── Open report ──────────────────────────────────────────────────────────────
if command -v open &>/dev/null; then
  open "$REPORT_FILE"
fi

# Exit with failure code if any tests failed
[[ $FAIL -eq 0 ]] || exit 1
